spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barber_db
    username: barber_user
    password: barber_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: barber-bucket
